/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppResumeRouteImport } from './routes/app.resume'
import { Route as AppProgressRouteImport } from './routes/app.progress'
import { Route as AppPathwayRouteImport } from './routes/app.pathway'
import { Route as AppJobsRouteImport } from './routes/app.jobs'
import { Route as AppGuideRouteImport } from './routes/app.guide'
import { Route as AppResumeIndexRouteImport } from './routes/app.resume.index'
import { Route as AppResumeBuilderRouteImport } from './routes/app.resume.builder'
import { Route as AppResumeAnalyzerRouteImport } from './routes/app.resume.analyzer'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppResumeRoute = AppResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppPathwayRoute = AppPathwayRouteImport.update({
  id: '/pathway',
  path: '/pathway',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppGuideRoute = AppGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AppRoute,
} as any)
const AppResumeIndexRoute = AppResumeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppResumeRoute,
} as any)
const AppResumeBuilderRoute = AppResumeBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AppResumeRoute,
} as any)
const AppResumeAnalyzerRoute = AppResumeAnalyzerRouteImport.update({
  id: '/analyzer',
  path: '/analyzer',
  getParentRoute: () => AppResumeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/guide': typeof AppGuideRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/pathway': typeof AppPathwayRoute
  '/app/progress': typeof AppProgressRoute
  '/app/resume': typeof AppResumeRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/resume/analyzer': typeof AppResumeAnalyzerRoute
  '/app/resume/builder': typeof AppResumeBuilderRoute
  '/app/resume/': typeof AppResumeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/guide': typeof AppGuideRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/pathway': typeof AppPathwayRoute
  '/app/progress': typeof AppProgressRoute
  '/app': typeof AppIndexRoute
  '/app/resume/analyzer': typeof AppResumeAnalyzerRoute
  '/app/resume/builder': typeof AppResumeBuilderRoute
  '/app/resume': typeof AppResumeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/guide': typeof AppGuideRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/pathway': typeof AppPathwayRoute
  '/app/progress': typeof AppProgressRoute
  '/app/resume': typeof AppResumeRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/resume/analyzer': typeof AppResumeAnalyzerRoute
  '/app/resume/builder': typeof AppResumeBuilderRoute
  '/app/resume/': typeof AppResumeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/app/guide'
    | '/app/jobs'
    | '/app/pathway'
    | '/app/progress'
    | '/app/resume'
    | '/app/'
    | '/app/resume/analyzer'
    | '/app/resume/builder'
    | '/app/resume/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/app/guide'
    | '/app/jobs'
    | '/app/pathway'
    | '/app/progress'
    | '/app'
    | '/app/resume/analyzer'
    | '/app/resume/builder'
    | '/app/resume'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/app/guide'
    | '/app/jobs'
    | '/app/pathway'
    | '/app/progress'
    | '/app/resume'
    | '/app/'
    | '/app/resume/analyzer'
    | '/app/resume/builder'
    | '/app/resume/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resume': {
      id: '/app/resume'
      path: '/resume'
      fullPath: '/app/resume'
      preLoaderRoute: typeof AppResumeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/progress': {
      id: '/app/progress'
      path: '/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pathway': {
      id: '/app/pathway'
      path: '/pathway'
      fullPath: '/app/pathway'
      preLoaderRoute: typeof AppPathwayRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jobs': {
      id: '/app/jobs'
      path: '/jobs'
      fullPath: '/app/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/guide': {
      id: '/app/guide'
      path: '/guide'
      fullPath: '/app/guide'
      preLoaderRoute: typeof AppGuideRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resume/': {
      id: '/app/resume/'
      path: '/'
      fullPath: '/app/resume/'
      preLoaderRoute: typeof AppResumeIndexRouteImport
      parentRoute: typeof AppResumeRoute
    }
    '/app/resume/builder': {
      id: '/app/resume/builder'
      path: '/builder'
      fullPath: '/app/resume/builder'
      preLoaderRoute: typeof AppResumeBuilderRouteImport
      parentRoute: typeof AppResumeRoute
    }
    '/app/resume/analyzer': {
      id: '/app/resume/analyzer'
      path: '/analyzer'
      fullPath: '/app/resume/analyzer'
      preLoaderRoute: typeof AppResumeAnalyzerRouteImport
      parentRoute: typeof AppResumeRoute
    }
  }
}

interface AppResumeRouteChildren {
  AppResumeAnalyzerRoute: typeof AppResumeAnalyzerRoute
  AppResumeBuilderRoute: typeof AppResumeBuilderRoute
  AppResumeIndexRoute: typeof AppResumeIndexRoute
}

const AppResumeRouteChildren: AppResumeRouteChildren = {
  AppResumeAnalyzerRoute: AppResumeAnalyzerRoute,
  AppResumeBuilderRoute: AppResumeBuilderRoute,
  AppResumeIndexRoute: AppResumeIndexRoute,
}

const AppResumeRouteWithChildren = AppResumeRoute._addFileChildren(
  AppResumeRouteChildren,
)

interface AppRouteChildren {
  AppGuideRoute: typeof AppGuideRoute
  AppJobsRoute: typeof AppJobsRoute
  AppPathwayRoute: typeof AppPathwayRoute
  AppProgressRoute: typeof AppProgressRoute
  AppResumeRoute: typeof AppResumeRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppGuideRoute: AppGuideRoute,
  AppJobsRoute: AppJobsRoute,
  AppPathwayRoute: AppPathwayRoute,
  AppProgressRoute: AppProgressRoute,
  AppResumeRoute: AppResumeRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
